### ISSUE TITLE
Performance test

### ISSUE THREAD

**Issue by flaviopalomba02** [cppcoffee/khttpd#12]
Hi! I've come across your HTTP server project integrated as a Linux kernel module. I'm curious to know if you've carried out any performance testing to evaluate the optimization advantages that come with having the server integrated within the kernel. If you have, could you please share the results with me? Thanks, and congratulations on your work.

**Comment by cppcoffee** [comment]
Oh, I'm really sorry, I didn't do a performance test on it.
